src/EndPoints/DigiLearn.Web/Areas/Admin/Pages/Teachers/Index.cshtml.cs
using CoreModule.Application.Teacher.ToggleStatus;
using CoreModule.Facade.Teacher;
using CoreModule.Query.Teacher._DTOs;
using DigiLearn.Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DigiLearn.Web.Areas.Admin.Pages.Teachers;

public class IndexModel(ITeacherFacade teacherFacade):BaseRazor
{

    public List<TeacherDto> Teachers { get; set; }

    public async Task OnGet()
    {
        Teachers = await teacherFacade.GetTeacherList();
    }


    public async Task<IActionResult> OnPostToggleStatus(Guid teacherId)
    {
        return await AjaxTryCatch(async () =>
        {
            var result = await teacherFacade.ToggleStatus(new ToggleTeacherStatusCommand(teacherId));
            return result;
        });
    }
}

src/EndPoints/DigiLearn.Web/Areas/Admin/Pages/Teachers/Show.cshtml.cs
using CoreModule.Application.Teacher.AcceptRequest;
using CoreModule.Application.Teacher.RejectRequest;
using CoreModule.Facade.Teacher;
using CoreModule.Query.Teacher._DTOs;
using DigiLearn.Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DigiLearn.Web.Areas.Admin.Pages.Teachers;

public class ShowModel(ITeacherFacade teacherFacade):BaseRazor
{
    public TeacherDto Teacher { get; set; }

    public async Task<IActionResult> OnGet(Guid teacherId)
    {
        var teacher = await teacherFacade.GetTeacherById(teacherId);

        if (teacher==null)
        {
            return RedirectToPage("Index");
        }

        Teacher = teacher;
        return Page();
    }


    public async Task<IActionResult> OnPostAccept(Guid teacherId)
    {
        

        return await AjaxTryCatch(async () =>
        {
            var result = await teacherFacade.AcceptRequest(new AcceptTeacherRequestCommand
            {
                TeacherId = teacherId
            });
            return result;
        });
    }


    public async Task<IActionResult> OnPostReject(Guid teacherId,string description)
    {
        var result = await teacherFacade.RejectRequest(new RejectTeacherRequestCommand
        {
            TeacherId = teacherId,
            Description = description
        });
        return RedirectAndShowAlert(result,RedirectToPage("show",new{teacherId}));
    }
}

src/EndPoints/DigiLearn.Web/Areas/Admin/Pages/Tickets/Show.cshtml.cs
using DigiLearn.Web.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Net.Sockets;
using Common.Application;
using DigiLearn.Web.Infrastructure.RazorUtils;
using TicketModule.Core.DTOs.Tickets;
using TicketModule.Core.Services;
using UserModule.Core.Services;

namespace DigiLearn.Web.Areas.Admin.Pages.Tickets;

public class ShowModel(ITicketService ticketService,IUserFacade userFacade) : BaseRazor
{
    public TicketDto? Ticket { get; set; }

    [BindProperty]
    [Display(Name = "متن پیام")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public string Text { get; set; }

    public async Task<IActionResult> OnGet(Guid ticketId)
    {
        var ticket = await ticketService.GetTicket(ticketId);
        if (ticket == null)
            return RedirectToPage("Index");

        Ticket = ticket;
        return Page();
    }

    public async Task<IActionResult> OnPost(Guid ticketId)
    {
        var user = await userFacade.GetUserByPhoneNumber(User.GetPhoneNumber());
        var message = new SendTicketMessageCommand
        {
            UserId = User.GetUserId(),
            TicketId = ticketId,
            OwnerFullName = $"{user!.Name}{user.Family}",
            Text = Text
        };
        var result = await ticketService.SendMessageInTicket(message);
        return RedirectAndShowAlert(result, RedirectToPage("Show", new { ticketId }));
    }

    public async Task<IActionResult> OnPostCloseTicket(Guid ticketId)
    {
        return await AjaxTryCatch(async () =>
        {
            var ticket = await ticketService.GetTicket(ticketId);
            if (ticket == null || ticket.UserId != User.GetUserId())
            {
                return OperationResult.Error("تیکت یافت نشد");
            }
            return await ticketService.CloseTicket(ticketId);
        });
    }
}

src/EndPoints/DigiLearn.Web/Pages/Profile/Teacher/Courses/Add.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Common.Domain.Utils;
using Common.Domain.ValueObjects;
using CoreModule.Application.Course.Create;
using CoreModule.Domain.Courses.Enums;
using CoreModule.Facade.Course;
using CoreModule.Facade.Teacher;
using DigiLearn.Web.Infrastructure;
using DigiLearn.Web.Infrastructure.RazorUtils;
using DigiLearn.Web.Infrastructure.Utils.CustomValidation.IFormFile;
using Microsoft.AspNetCore.Mvc;

namespace DigiLearn.Web.Pages.Profile.Teacher.Courses;

[BindProperties]
[ServiceFilter(typeof(TeacherActionFilter))]
public class AddModel(ICourseFacade courseFacade, ITeacherFacade teacherFacade) : BaseRazor
{
    [Display(Name = "دسته بندی اصلی")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public Guid CategoryId { get; set; }


    [Display(Name = "زیر دسته بندی")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public Guid SubCategoryId { get; set; }


    [Display(Name = "عنوان انگلیسی دوره")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public string Slug { get; set; }


    [Display(Name = " عنوان دوره")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public string Title { get; set; }


    [Display(Name = "توضیحات دوره")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    [UIHint("Ckeditor4")]
    public string Description { get; set; }


    [Display(Name = "عکس دوره")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    [FileImage(ErrorMessage = "عکس دوره نامعتبر می باشد")]
    public IFormFile ImageFile { get; set; }


    [Display(Name = "دمو دوره")]
    [FileType("mp4",ErrorMessage = "ویدیو معرفی نامعتبز هست")]
    public IFormFile? VideoFile { get; set; }


    [Display(Name = "قیمت دوره")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public int Price { get; set; }


    [Display(Name = "سطح دوره")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public CourseLevel CourseLevel { get; set; }



    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPost()
    {
        var teacher = await teacherFacade.GetTeacherByUserId(User.GetUserId());

        var command = new CreateCourseCommand
        {
            TeacherId = teacher!.Id,
            CategoryId = CategoryId,
            SubCategoryId = SubCategoryId,
            Slug = Slug.ToSlug(),
            Title = Title,
            Description = Description,
            ImageFile = ImageFile,
            VideoFile = VideoFile,
            Price = Price,
            CourseLevel = CourseLevel,
            Status = CourseActionStatus.Pending,
            SeoData = new SeoData(Title, Title, Title, null)
        };
        var result = await courseFacade.Create(command);
        return RedirectAndShowAlert(result, RedirectToPage("Index"));
    }
}

src/EndPoints/DigiLearn.Web/Pages/Profile/Teacher/Courses/Index.cshtml.cs
using CoreModule.Facade.Course;
using CoreModule.Facade.Teacher;
using CoreModule.Query.Course._DTOs;
using CoreModule.Query.Teacher._DTOs;
using DigiLearn.Web.Infrastructure;
using DigiLearn.Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;

namespace DigiLearn.Web.Pages.Profile.Teacher.Courses;

[ServiceFilter(typeof(TeacherActionFilter))]
public class IndexModel(ICourseFacade coursedFacade, ITeacherFacade teacherFacade) : BaseRazorFilter<CourseFilterParams>
{
    public CourseFilterResult FilterResult { get; set; }

    public TeacherDto Teacher { get; set; }

    public async Task OnGet()
    {
        var teacher = await teacherFacade.GetTeacherByUserId(User.GetUserId());
        FilterParams.TeacherId = teacher!.Id;
        FilterResult = await coursedFacade.GetCourseByFilter(FilterParams);
    }
}

src/EndPoints/DigiLearn.Web/Pages/Profile/Teacher/Courses/Sections/Add.cshtml.cs
using System.ComponentModel.DataAnnotations;
using CoreModule.Application.Course.Sections.AddSection;
using CoreModule.Facade.Course;
using DigiLearn.Web.Infrastructure;
using DigiLearn.Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;

namespace DigiLearn.Web.Pages.Profile.Teacher.Courses.Sections;

[ServiceFilter(typeof(TeacherActionFilter))]
[BindProperties]
public class AddModel(ICourseFacade courseFacade) : BaseRazor
{
    [Display(Name = "عنوان")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public string Title { get; set; }


    [Display(Name = "ترتیب نمایش")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public int DisplayOrder { get; set; }

    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPost(Guid courseId)
    {
        var result = await courseFacade.AddSection(new AddCourseSectionCommand
        {
            CourseId = courseId,
            Title = Title,
            DisplayOrder = DisplayOrder
        });

        return RedirectAndShowAlert(result, RedirectToPage("Index", new{ courseId }));
    }
}

src/EndPoints/DigiLearn.Web/Pages/Profile/Teacher/Courses/Sections/Episodes/Add.cshtml.cs
using System.ComponentModel.DataAnnotations;
using CoreModule.Application.Course.Episodes.Add;
using CoreModule.Facade.Course;
using DigiLearn.Web.Infrastructure;
using DigiLearn.Web.Infrastructure.RazorUtils;
using DigiLearn.Web.Infrastructure.Utils.CustomValidation.IFormFile;
using Microsoft.AspNetCore.Mvc;

namespace DigiLearn.Web.Pages.Profile.Teacher.Courses.Sections.Episodes;

[ServiceFilter(typeof(TeacherActionFilter))]
[BindProperties]
public class AddModel(ICourseFacade courseFacade):BaseRazor
{

    [Display(Name = "عنوان")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public string Title { get; set; }


    [Display(Name = "عنوان انگلیسی")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public string EnglishTitle { get; set; }


    [Display(Name = "مدت زمان")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    [RegularExpression(@"^([0-9]{1}|(?:0[0-9]|1[0-9]|2[0-3])+):([0-5]?[0-9])(?::([0-5]?[0-9])(?:.(\d{1,9}))?)?$", ErrorMessage = "لطفا زمان را با فرمت درست وارد کنید")]
    public TimeSpan TimeSpan { get; set; }


    [Display(Name = "ویدیو")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    [FileType("mp4",ErrorMessage = "ویدیو نامعتبر میباشد")]
    public IFormFile VideoFile { get; set; }


    [Display(Name = "فایل ضمیمه")]
    [FileType("rar",ErrorMessage = "فایل ضمیمه نامعتبر میباشد")]
    public IFormFile? AttachmentFile { get; set; }


    [Display(Name = "این قسمت رایگان است")]
    public bool IsFree { get; set; }


    public void OnGet()
    {
    }
    public async Task<IActionResult> OnPost(Guid courseId, Guid sectionId)
    {
        var result = await courseFacade.AddEpisode(new AddCourseEpisodeCommand
        {
            CourseId = courseId,
            SectionId = sectionId,
            Title = Title,
            EnglishTitle = EnglishTitle,
            TimeSpan = TimeSpan,
            VideoFile = VideoFile,
            AttachmentFile = AttachmentFile,
            IsActive = false,
            IsFree = IsFree,
        });
        return RedirectAndShowAlert(result, RedirectToPage("../Index", new { courseId }));
    }

}

src/EndPoints/DigiLearn.Web/Pages/Profile/Teacher/Courses/Sections/Index.cshtml.cs
using CoreModule.Facade.Course;
using CoreModule.Facade.Teacher;
using CoreModule.Query.Course._DTOs;
using DigiLearn.Web.Infrastructure;
using DigiLearn.Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;

namespace DigiLearn.Web.Pages.Profile.Teacher.Courses.Sections;

[ServiceFilter(typeof(TeacherActionFilter))]
public class IndexModel(ICourseFacade courseFacade, ITeacherFacade teacherFacade) : BaseRazor
{
    public CourseDto Course { get; set; }

    public async Task<IActionResult> OnGet(Guid courseId)
    {
        var course = await courseFacade.GetCourseById(courseId);
        var teacher = await teacherFacade.GetTeacherByUserId(User.GetUserId());
        if (course == null || course.TeacherId!=teacher!.Id)
        {
            return RedirectToPage("../Index");
        }
        Course = course;
        return Page();
    }
}

src/EndPoints/DigiLearn.Web/Pages/Profile/Tickets/Show.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Common.Application;
using DigiLearn.Web.Infrastructure;
using DigiLearn.Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;
using TicketModule.Core.DTOs.Tickets;
using TicketModule.Core.Services;
using UserModule.Core.Services;

namespace DigiLearn.Web.Pages.Profile.Tickets;


public class ShowModel(ITicketService ticketService,IUserFacade userFacade) : BaseRazor
{
    public TicketDto?  Ticket { get; set; }

    [BindProperty]
    [Display(Name = "متن پیام")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public string Text { get; set; }

    public async Task<IActionResult> OnGet(Guid ticketId)
    {
        var ticket = await ticketService.GetTicket(ticketId);
        if (ticket == null || ticket.UserId != User.GetUserId())
            return RedirectToPage("Index");


        Ticket = ticket;
        return Page();
    }

    public async Task<IActionResult> OnPost(Guid ticketId)
    {
        var user = await userFacade.GetUserByPhoneNumber(User.GetPhoneNumber());
        var message = new SendTicketMessageCommand
        {
            UserId = User.GetUserId(),
            TicketId = ticketId,
            OwnerFullName =$"{user!.Name}{user.Family}" ,
            Text = Text
        };
        var result =await ticketService.SendMessageInTicket(message);
        return RedirectAndShowAlert(result, RedirectToPage("Show",new {ticketId}));
    }

    public async Task<IActionResult> OnPostCloseTicket(Guid ticketId)
    {
        return await AjaxTryCatch(async () =>
        {
            var ticket=await ticketService.GetTicket(ticketId);
            if (ticket==null || ticket.UserId!=User.GetUserId())
            {
                return OperationResult.Error("تیکت یافت نشد");
            }
            return await ticketService.CloseTicket(ticketId);
        });
    }
}

src/EndPoints/DigiLearn.Web/Areas/Admin/Pages/Teachers/Index.cshtml
@page "{handler?}"
@using CoreModule.Domain.Teachers.Enums
@model DigiLearn.Web.Areas.Admin.Pages.Teachers.IndexModel
@{
    ViewData["title"] = "مدیریت مدرسین";
    ViewData["selected"] = "teachers";
}


<div class="card">
    <div class="table table-responsive card-body p-0 mb-0">
        <table class="table table-bordered table-hover mb-0 data-table">
            <thead>
                <tr>
                    <th>نام کاربری</th>
                    <th>نام ونام خانوادگی</th>
                    <th>شماره تلفن</th>
                    <th>وضعیت</th>
                    <th>عملیات</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Teachers)
                {
                    <tr>
                        <td>@item.UserName</td>
                        <td>@item.User.Name @item.User.Family</td>
                        <td>@item.User.PhoneNumber</td>
                        <td>
                            @switch (@item.Status)
                            {
                                case TeacherStatus.Active:
                                    <label class="badge badge-success">فعال</label>
                                    break;
                                case TeacherStatus.InActive:
                                    <label class="badge badge-danger">غیرفعال</label>
                                    break;
                                case TeacherStatus.Pending:
                                    <label class="badge badge-info">درحال بررسی</label>
                                    break;

                                default:
                                    throw new ArgumentOutOfRangeException();
                            }
                        </td>


                            <td>
                                @if (item.Status == TeacherStatus.InActive)
                            {
                                <Question class="btn btn-danger" url="@Url.Page("Index","ToggleStatus",new{teacherId=item.Id})">فعال سازی</Question>
                            }
                            else if (item.Status == TeacherStatus.Active)
                                {
                                <Question class="btn btn-success" url="@Url.Page("Index","ToggleStatus",new{teacherId=item.Id})">غیر فعال سازی</Question>
                            }


                            <a class="btn btn-primary " asp-page="Show" asp-route-teacherId="@item.Id">نمایش</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    @*<partial name="_Pagination"model="null"/>*@
</div>

src/EndPoints/DigiLearn.Web/Areas/Admin/Pages/Teachers/Show.cshtml
@page "{teacherId}/{handler?}"
@using UserModule.Core
@using CoreModule.Application._Utilities
@using Common.Application.DateUtil
@using CoreModule.Domain.Teachers.Enums
@model DigiLearn.Web.Areas.Admin.Pages.Teachers.ShowModel
@{
    ViewData["title"] = "مدیزیت اطلاعات مدرس";
    ViewData["selected"] = "teachers";
}

<h2>اطلاعات مدرس</h2>
@if (Model.Teacher.Status == TeacherStatus.Pending)
{
    <Question class="btn btn-success" url="@Url.Page("show","Accept",new{teacherId=Model.Teacher.Id})">تایید درخواست</Question>
}


<div class="card card-body mt-1">
    <img src="@UserModuleDirectories.GetUserAvatar(Model.Teacher.User.Avatar)" style="max-width: 150px" class="mb-2" />
    <div class="row">
        <div class="col-md-6">نام کاربری : @Model.Teacher.UserName</div>
        <div class="col-md-6">نام و نام خانوادگی : @Model.Teacher.User.Name @Model.Teacher.User.Family</div>

        <div class="col-md-6">شماره تلفن : @Model.Teacher.User.PhoneNumber</div>

        <div class="col-md-6">ایمیل : @Model.Teacher.User.Email</div>

        <div class="col-md-6">تاریخ ثبت نام : @Model.Teacher.CreationDate.ToPersianDateTime()</div>

        <div class="col-md-6">
            وضعیت :
            @switch (Model.Teacher.Status)
            {
                case TeacherStatus.Active:
                    <label class="badge bg-success">فعال</label>
                    break;
                case TeacherStatus.InActive:
                    <label class="badge bg-danger">غیرفعال</label>

                    break;

                case TeacherStatus.Pending:
                    <label class="badge bg-primary">درحال برسی</label>

                    break;
            }
        </div>
        <div class="col-md-12">رزومه : <a href="@CoreModuleDirectories.GetCvFile(Model.Teacher.CvFileName)" target="_blank">نمایش</a></div>
    </div>
</div>

@if (Model.Teacher.Status == TeacherStatus.Pending)
{
    <div class="card card-body mt-2">
        <form method="post" asp-page-handler="Reject">
            <textarea class="form-control" name="description" placeholder="دلیل رد درخواست"></textarea>
            <button class="btn btn-danger mt-1" onclick="return confirm('ایا از انجام عملیات اطمینان دارید؟')">رددرخواست</button>
        </form>
    </div>
}
   